### ISSUE TITLE
[Propunere] Editare canal

### ISSUE THREAD

**Issue by condor2** [ov1d1u/tv-maxe-ng#1]
Salut

Se poate adauga si functia de Editare Canal?
Daca la adaugarea unui canal se gresete numele, sau adresa, sa se poata edita rapid fara a sterge :)

Ms

**Comment by derzis** [comment]
derzis@manjaro tv-maxe]$ python tvmaxe.py 
INFO:__main__:TV-Maxe 0.1a
INFO:mainwindow:Detected OS type: Linux
Traceback (most recent call last):
  File "/home/derzis/tv-maxe-ng/tv-maxe/mainwindow.py", line 139, in channel_added
    self.tv_channel_list.addChannel(channel)
  File "/home/derzis/tv-maxe-ng/tv-maxe/channellistwidget.py", line 40, in addChannel
    channel_item = ChannelItem(channel)
  File "/home/derzis/tv-maxe-ng/tv-maxe/channelitem.py", line 10, in __init__
    self.channel = channel
  File "/home/derzis/tv-maxe-ng/tv-maxe/channelitem.py", line 21, in channel
    image.loadFromData(channel.icon)
TypeError: arguments did not match any overloaded call:
  loadFromData(self, bytes, format: str = None): argument 1 has unexpected type 'str'
  loadFromData(self, Union[QByteArray, bytes, bytearray], format: str = None): argument 1 has unexpected type 'str'
Aborted (core dumped)
